"""UI package exports."""

from media_dl.ui.console import get_console, reset_console
from media_dl.ui.menus import (
    pause,
    show_error_panel,
    show_header,
    show_info_panel,
    show_main_menu,
    show_menu,
    show_success_panel,
    show_warning_panel,
)
from media_dl.ui.prompts import (
    parse_range,
    prompt_audio_bitrate,
    prompt_audio_format,
    prompt_config_value,
    prompt_directory,
    prompt_file_path,
    prompt_int_range,
    prompt_playlist_range,
    prompt_quality,
    prompt_subtitle_languages,
    prompt_url,
    prompt_urls_batch,
    prompt_yes_no,
)
from media_dl.ui.tables import (
    create_config_table,
    create_format_table,
    create_history_table,
    create_media_info_table,
    create_playlist_table,
    create_stats_table,
    create_system_info_table,
    format_duration,
    format_size,
)
from media_dl.ui.theme import CYAN_THEME

__all__ = [
    "CYAN_THEME",
    "create_config_table",
    "create_format_table",
    "create_history_table",
    "create_media_info_table",
    "create_playlist_table",
    "create_stats_table",
    "create_system_info_table",
    "format_duration",
    "format_size",
    "get_console",
    "parse_range",
    "pause",
    "prompt_audio_bitrate",
    "prompt_audio_format",
    "prompt_config_value",
    "prompt_directory",
    "prompt_file_path",
    "prompt_int_range",
    "prompt_playlist_range",
    "prompt_quality",
    "prompt_subtitle_languages",
    "prompt_url",
    "prompt_urls_batch",
    "prompt_yes_no",
    "reset_console",
    "show_error_panel",
    "show_header",
    "show_info_panel",
    "show_main_menu",
    "show_menu",
    "show_success_panel",
    "show_warning_panel",
]
