import './index.css';

const tools = {
  '/analizador-imagenes': ['Analizador de imágenes', 'Lectura local / imagen', 'Inspecciona dimensiones, formato, peso y metadatos básicos sin subir el archivo a ningún servidor.', 'image/*', ['Dimensiones y relación de aspecto', 'Tipo MIME y tamaño exacto', 'Hash SHA-256 del archivo']],
  '/analizador-audio': ['Analizador de audio', 'Lectura local / audio', 'Obtén una ficha técnica honesta de tus archivos de audio. El navegador lee lo que el contenedor expone, sin inventar señales.', 'audio/*', ['Duración y tipo de contenedor', 'Tamaño y nombre de archivo', 'Hash SHA-256 del archivo']],
  '/analizador-video': ['Analizador de video', 'Lectura local / video', 'Revisa duración, dimensiones y compatibilidad del navegador con una vista previa local.', 'video/*', ['Resolución y relación de aspecto', 'Duración leída por el navegador', 'Hash SHA-256 del archivo']],
  '/analizador-texto': ['Analizador de texto', 'Lectura local / texto', 'Cuenta líneas, caracteres, palabras y estructura básica de archivos de texto manteniendo el contenido en tu dispositivo.', '.txt,.md,.csv,.json,.xml,.log,text/*', ['Conteo de caracteres y palabras', 'Detección de líneas vacías', 'Hash SHA-256 del archivo']],
  '/analizador-codigo': ['Analizador de código', 'Lectura local / código', 'Una lectura rápida de estructura, comentarios y densidad. Es heurística: no reemplaza una auditoría de seguridad.', '.js,.ts,.tsx,.jsx,.css,.html,.py,.json,.sql,.java,.go,.rs,.php', ['Líneas y densidad de comentarios', 'Extensión y tipo de archivo', 'Hash SHA-256 del archivo']]
};
const nav = [['Espacio de trabajo', [['/', 'Inicio', '▦'], ['/galeria', 'Galería', '▦'], ['/historial', 'Historial', '◷']]],
  ['Herramientas locales', Object.entries(tools).map(([p, v]) => [p, v[0], '▣']).concat([['/convertidor', 'Convertidor', '↻']])],
  ['Servicios externos', [['/descargar-video', 'Descargar video', '▶'], ['/descargar-musica', 'Descargar música', '♫'], ['/tiktok', 'TikTok', '▶'], ['/generador-imagenes', 'Generador de imágenes', '✦']]]];
const external = {
  '/descargar-video': ['Descargar video', 'Servicio externo / video', 'No conectamos con plataformas protegidas ni extraemos contenido de terceros.', ['Pega una URL solo para identificar el servicio, no para descargar.', 'El navegador no recibe ni guarda la URL en un servidor.', 'Usa el analizador local cuando tengas el archivo con permiso.']],
  '/descargar-musica': ['Descargar música', 'Servicio externo / audio', 'La descarga desde servicios externos no está disponible en esta estación local.', ['No se simulan enlaces de descarga.', 'No se accede a catálogos ni cuentas de terceros.', 'Los archivos propios sí pueden analizarse localmente.']],
  '/tiktok': ['TikTok', 'Servicio externo / plataforma', 'Este módulo documenta el límite: no descarga, no elimina marcas de agua y no consulta perfiles externos.', ['Sin scraping de perfiles o publicaciones.', 'Sin almacenamiento de URLs externas.', 'Puedes analizar un video local autorizado.']],
  '/generador-imagenes': ['Generador de imágenes', 'Modelo externo / creación', 'La generación de imágenes necesita un modelo o servicio externo. Esta versión no inventa una imagen ni finge que la ha generado.', ['No se realiza ninguna llamada a una API de IA.', 'Puedes preparar un prompt y copiarlo para usarlo en tu herramienta.', 'La salida debe revisarse y atribuirse fuera de LC Systems.']]
};
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes = n => { if (!n) return '0 B'; const u=['B','KB','MB','GB'], i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3); return `${(n/1024**i).toFixed(i?1:0)} ${u[i]}`; };
const history = () => { try { return JSON.parse(localStorage.getItem('lc-history') || '[]'); } catch { return []; } };
const download = (blob, name) => { const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); };
const icon = x => `<span class="text-icon" aria-hidden="true">${x}</span>`;
let menu = false, toastTimer;
function toast(message, kind='info') { const n=document.createElement('div'); n.className='toast'; n.innerHTML=`${icon(kind==='ok'?'✓':kind==='error'?'×':'i')}<span>${esc(message)}</span>`; $('.toast-stack').append(n); clearTimeout(toastTimer); toastTimer=setTimeout(()=>n.remove(),4200); }
function shell(path, body) {
  const current = nav.flatMap(g=>g[1]).find(x=>x[0]===path);
  return `<div class="app-shell"><aside class="sidebar ${menu?'open':''}"><a class="brand" href="#/"><span class="brand-mark">L</span><span><span class="brand-name">LC Systems</span><span class="brand-sub">media intelligence</span></span></a><nav>${nav.map(g=>`<div><div class="nav-label">${g[0]}</div><div class="nav">${g[1].map(x=>`<a class="nav-link ${x[0]===path?'active':''}" href="#${x[0]}">${icon(x[2])}<span>${x[1]}</span></a>`).join('')}</div></div>`).join('')}</nav><div class="sidebar-foot"><strong>100% local-first</strong>Tus archivos permanecen en este navegador. No conectamos con plataformas ni servidores externos.</div></aside><main class="main"><header class="topbar"><div class="top-actions"><button class="icon-btn mobile-menu" data-action="menu">☰</button><div class="crumb"><strong>${current?.[1] || (path==='/'?'Inicio':'LC Systems')}</strong> <span>/ navegador local</span></div></div><div class="top-actions"><div class="status-pill"><span class="status-dot"></span> entorno local activo</div><a class="icon-btn" href="#/configuracion">⚙</a></div></header><div class="content">${body}</div></main><div class="toast-stack" aria-live="polite"></div></div>`;
}
const page = (ey, title, lead, body) => `<div class="eyebrow">${ey}</div><h1 class="page-title">${title}</h1><p class="page-lead">${lead}</p>${body}`;
const button = (label, action, cls='btn btn-primary') => `<button class="${cls}" data-action="${action}">${label}</button>`;
function home() {
 const h=history(); const cards=[['/analizador-imagenes','Imágenes','Dimensiones, formato y metadatos','▣'],['/analizador-audio','Audio','Duración y ficha del contenedor','♫'],['/analizador-video','Video','Resolución, duración y vista previa','▶'],['/analizador-texto','Texto','Conteo, estructura y lectura local','▤'],['/analizador-codigo','Código','Estructura y señales heurísticas','{}'],['/convertidor','Convertidor','Prepara flujos compatibles','↻'],['/galeria','Galería','Revisa tus archivos procesados','▦'],['/historial','Historial','Informes guardados en este navegador','◷']];
 return `<div class="hero-grid"><section class="hero-panel"><div><div class="eyebrow" style="color:hsl(var(--mint))">LC / estación de trabajo 01</div><h2>Ver primero.<br>Concluir después.</h2><p>Un espacio preciso para inspeccionar medios locales, entender sus límites y dejar una pista técnica que puedas volver a revisar.</p></div><div class="hero-foot"><div class="hero-metric"><span>PRIVACIDAD</span>sin subidas</div><div class="hero-metric"><span>RESPUESTA</span>en tu navegador</div><div class="hero-metric"><span>RIGOR</span>heurístico, explícito</div></div></section><section class="signal-card"><div><div class="eyebrow">actividad local</div><div class="big-number">${String(h.length).padStart(2,'0')}</div><div class="small">informes creados en este dispositivo. Se guardan únicamente en localStorage.</div></div><div class="scanline">${'<i></i>'.repeat(10)}</div></section></div><div class="section-heading"><div><h2>Herramientas a mano</h2><p>Selecciona un archivo y empieza sin configurar nada.</p></div><a href="#/ayuda" class="btn btn-ghost">Cómo funciona ↗</a></div><div class="tool-grid">${cards.map(c=>`<a class="tool-card" href="#${c[0]}"><span class="tool-icon">${icon(c[3])}</span><span><h3>${c[1]}</h3><p>${c[2]}</p></span><span class="arrow">›</span></a>`).join('')}</div><div class="info-strip">${icon('✓')}<span><strong>Alcance claro.</strong> Las descargas desde plataformas externas, la generación de imágenes y cualquier conclusión forense requieren servicios o modelos que esta versión local no conecta.</span></div><div class="section-heading"><div><h2>Tu pulso local</h2><p>Una vista rápida de lo que ya procesaste.</p></div><a href="#/historial" class="btn btn-ghost">Ver historial ↗</a></div><div class="metrics"><div class="metric-card"><div class="metric-label">Informes guardados</div><div class="metric-value">${h.length}</div><div class="metric-note">persistidos en este navegador</div></div><div class="metric-card"><div class="metric-label">Último procesamiento</div><div class="metric-value" style="font-size:17px">${h[0]?.date||'aún no hay datos'}</div><div class="metric-note">sin actividad en red</div></div><div class="metric-card"><div class="metric-label">Archivos en sesión</div><div class="metric-value">${h.filter(x=>x.status==='Completado').length}</div><div class="metric-note">resultados descriptivos</div></div></div>`;
}
function localTool(path) {
 const c=tools[path]; let file=null, hash='', report='', state='idle';
 const render=()=>{ const extra=file && (path.includes('texto')||path.includes('codigo')) ? `\nLíneas: ${file._lines}\nPalabras: ${file._words}\nCaracteres: ${file._chars}\nLíneas vacías: ${file._blank}` : ''; return page(c[1],c[0],c[2],`<div class="tool-layout"><section class="panel"><h2>Entrada local</h2><p class="panel-sub">Suelta un archivo o selecciónalo. El procesamiento ocurre en esta pestaña.</p><div class="dropzone ${state==='loading'?'dragging':''}" data-dropzone><input id="file-input" type="file" accept="${c[3]}"><div style="font-size:28px">${icon('↑')}</div><h3>${file?'Archivo listo para revisar':'Suelta tu archivo aquí'}</h3><p>${file?'Puedes reemplazarlo seleccionando otro archivo.':`Formatos aceptados según el navegador · ${c[3]}`}</p>${button(file?'Elegir otro archivo':'Seleccionar archivo','choose')}</div>${file?`<div class="file-chip">${icon('▣')}<div><strong>${esc(file.name)}</strong><span>${bytes(file.size)} · ${esc(file.type||'tipo no declarado')}</span></div>${icon('✓')}</div>`:''}${state==='loading'?'<div class="process-box loading">Calculando hash y leyendo señales del archivo…<div class="progress-track"><div class="progress-fill"></div></div></div>':''}${state==='success'?'<div class="process-box"><strong>Lectura completada.</strong> No se realizó ninguna subida.</div>':''}</section><aside class="panel"><h2>Qué vamos a comprobar</h2><p class="panel-sub">Señales descriptivas, no una sentencia sobre el origen o autenticidad del archivo.</p><div class="check-list">${c[4].map(x=>`<div class="check-item">${icon('✓')}${x}</div>`).join('')}</div>${file&&state==='success'?`<div class="metadata"><div class="meta-item"><span>Extensión</span><strong>${esc(file.name.includes('.')?file.name.split('.').pop().toUpperCase():'ARCHIVO')}</strong></div><div class="meta-item"><span>Tamaño</span><strong>${bytes(file.size)}</strong></div><div class="meta-item"><span>Tipo MIME</span><strong>${esc(file.type||'n/d')}</strong></div><div class="meta-item"><span>Resultado</span><strong style="color:hsl(var(--mint-deep))">LOCAL</strong></div></div><div class="button-row">${button('Copiar hash','copy','btn btn-secondary')}${button('Exportar informe','report')}</div>`:''}</aside></div>${report?`<section class="panel" style="margin-top:18px"><div class="section-heading" style="margin:0"><div><h2>Informe listo</h2><p>Guárdalo para documentar qué leyó el navegador.</p></div><span class="badge">SHA-256 calculado</span></div><pre class="report">${esc(report)}</pre><div class="button-row">${button(`${hash.slice(0,18)}…`,'copy','btn btn-ghost')}</div></section>`:''}`); };
 const draw=()=>{ $('#app').innerHTML=shell(path,render()); bind(); bindGlobal(); };
 const bind=()=>{ const dz=$('[data-dropzone]'); $('#file-input')?.addEventListener('change',e=>process(e.target.files[0])); dz?.addEventListener('dragover',e=>{e.preventDefault();dz.classList.add('dragging')}); dz?.addEventListener('dragleave',()=>dz.classList.remove('dragging')); dz?.addEventListener('drop',e=>{e.preventDefault();process(e.dataTransfer.files[0])}); };
 const process=async f=>{if(!f)return;file=f;state='loading';draw();try{const b=await f.arrayBuffer(); hash=crypto.subtle?Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b))).map(x=>x.toString(16).padStart(2,'0')).join(''):'No disponible en este contexto'; if(path.includes('texto')||path.includes('codigo')){const t=await f.text(), lines=t.split(/\r?\n/);f._lines=lines.length;f._words=t.trim()?t.trim().split(/\s+/).length:0;f._chars=t.length;f._blank=lines.filter(x=>!x.trim()).length} const extra=path.includes('texto')||path.includes('codigo')?`\nLíneas: ${f._lines}\nPalabras: ${f._words}\nCaracteres: ${f._chars}\nLíneas vacías: ${f._blank}`:'\nInformación avanzada depende de lo que exponga el navegador.'; report=`LC SYSTEMS / INFORME LOCAL\n================================\nHerramienta: ${c[0]}\nArchivo: ${f.name}\nTipo MIME: ${f.type||'no declarado'}\nTamaño: ${bytes(f.size)}\nProcesado: ${new Date().toLocaleString('es-ES')}\nSHA-256: ${hash}\n\nNOTA DE ALCANCE\nEste informe fue creado en el navegador. No se enviaron datos a un servidor.\n${extra}`;state='success';const item={id:crypto.randomUUID?.()||Date.now(),name:f.name,tool:c[0],size:bytes(f.size),date:new Date().toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'}),status:'Completado',hash,report};localStorage.setItem('lc-history',JSON.stringify([item,...history()].slice(0,40)));draw();toast('Archivo procesado localmente. El informe ya está disponible.','ok')}catch(e){state='error';draw();toast(e.message||'No se pudo leer el archivo.','error')}};
 draw(); return;
}
function externalPage(path){const d=external[path];return page(d[1],d[0],d[2],`<div class="tool-layout"><section class="panel"><div class="dropzone" style="min-height:230px;border-style:solid;border-color:hsl(var(--yellow) / .7);background:hsl(var(--yellow) / .14)">${icon('✦')}<h3>Función bloqueada con transparencia</h3><p>El módulo está presente para explicar el alcance real del producto, no para simular una integración.</p><span class="badge" style="margin-top:15px">SERVICIO NO CONECTADO</span></div><label class="input-label">Referencia local (opcional)</label><input class="input" id="external-note" placeholder="Pega una URL o nota para tu registro…"><div class="button-row">${button('Copiar referencia','copy-reference','btn btn-secondary')}<a href="#/analizador-video" class="btn btn-primary">Analizar archivo local ↗</a></div></section><aside class="panel"><h2>Por qué</h2><div class="check-list">${d[3].map(x=>`<div class="check-item">${icon('✓')}${x}</div>`).join('')}</div><div class="process-box" style="margin-top:24px">Estado: <strong>capacidad no disponible</strong><br>No hay llamada de red, descarga ni resultado oculto.</div></aside></div>`)}
function historyPage(){const h=history();return page('Registro local / trazabilidad','Historial','Informes creados en este navegador. No es una nube ni una base de datos: puedes eliminarlo cuando quieras.',`<div class="button-row">${button('Exportar JSON','export-json','btn btn-secondary')}${button('Limpiar historial','clear-history','btn btn-ghost')}</div><div class="table-wrap">${h.length?`<table class="table"><thead><tr><th>Archivo</th><th>Herramienta</th><th>Tamaño</th><th>Fecha</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${h.map((x,i)=>`<tr><td><strong>${esc(x.name)}</strong><div class="mono">${x.hash?.slice(0,18)}…</div></td><td>${esc(x.tool)}</td><td>${x.size}</td><td>${x.date}</td><td><span class="badge">${x.status}</span></td><td>${button('↓',`download-history-${i}`,'icon-btn')}</td></tr>`).join('')}</tbody></table>`:`<div class="empty">${icon('◷')}<h3>Tu historial está despejado</h3><p>Procesa un archivo local y aquí aparecerá su informe, hash y fecha.</p><a href="#/analizador-imagenes" class="btn btn-primary">Analizar un archivo</a></div>`}</div>`)}
function simplePage(path){if(path==='/')return home();if(tools[path])return localTool(path);if(external[path])return externalPage(path);if(path==='/historial')return historyPage();if(path==='/galeria'){const h=history();return page('Resultados locales / vistazo','Galería','Una vista compacta de los archivos que ya pasaron por una herramienta.',h.length?`<div class="tool-grid" style="margin-top:27px">${h.map(x=>`<div class="tool-card"><div class="tool-icon">${icon('▣')}</div><div><h3>${esc(x.name)}</h3><p>${esc(x.tool)} · ${x.size}</p></div><span class="badge">guardado</span></div>`).join('')}</div>`:`<div class="empty"><h3>Aún no hay piezas en tu galería</h3><p>Los resultados aparecen después de procesar un archivo local.</p></div>`)};if(path==='/convertidor')return page('Flujo local / preparación','Convertidor','Prepara un archivo para una herramienta compatible. La conversión multimedia completa depende de códecs del navegador.',`<section class="panel" style="margin-top:28px"><h2>Preparar archivo</h2><p class="panel-sub">No se genera un archivo roto con una extensión distinta.</p><input class="input" type="file" id="converter-file"><select class="select" style="margin-top:12px"><option>MP4</option><option>MP3</option><option>WAV</option><option>WEBM</option></select><div class="process-box" style="margin-top:18px">La conversión completa no está disponible sin códecs locales.</div></section>`);if(path==='/configuracion')return page('Preferencias / dispositivo','Configuración','Controla cómo este navegador conserva tus rastros de trabajo. No hay cuenta ni sincronización.',`<div class="settings-grid"><div class="setting-card"><div class="toggle"><div><h3>Guardar historial local</h3><p>Conserva informes y hashes en localStorage.</p></div><button class="toggle-switch ${localStorage.getItem('lc-autosave')!=='false'?'on':''}" data-action="autosave"><i></i></button></div></div><div class="setting-card"><h3>Datos guardados</h3><p>LC Systems no tiene una base de datos.</p><a href="#/historial" class="btn btn-secondary">Gestionar historial</a></div></div>`);if(path==='/ayuda')return page('Manual breve / alcance','Trabaja con señales, no con promesas.','LC Systems es una estación de inspección en el navegador.',`<div class="help-grid">${[['Privacidad por defecto','Los archivos se leen con APIs del navegador. No se cargan ni envían.'],['Resultado descriptivo','Un hash demuestra que dos bytes coinciden, no su autenticidad.'],['Persistencia ligera','El historial vive en localStorage y puede borrarse.']].map(x=>`<div class="help-card"><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('')}</div>`);return page('LC Systems','Página no encontrada','La ruta solicitada no existe.',`<a href="#/" class="btn btn-primary">Volver al inicio</a>`)}
function render(){let p=location.hash.slice(1)||'/';if(tools[p]){localTool(p);return}const result=simplePage(p);$('#app').innerHTML=shell(p,result);bindGlobal()}
function bindGlobal(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const a=b.dataset.action;if(a==='menu'){menu=!menu;render()}if(a==='choose')$('#file-input')?.click();if(a==='copy'){const r=document.querySelector('.report')?.textContent||'';const m=r.match(/SHA-256: (.*)/);if(m)navigator.clipboard?.writeText(m[1]).then(()=>toast('Hash SHA-256 copiado.','ok'))}if(a==='report'){const r=document.querySelector('.report')?.textContent;if(r)download(new Blob([r],{type:'text/plain'}),'lc-informe.txt')}if(a==='copy-reference'){await navigator.clipboard?.writeText($('#external-note')?.value||'LC Systems: flujo externo no disponible en modo local.');toast('Referencia copiada.','ok')}if(a==='export-json')download(new Blob([JSON.stringify(history(),null,2)],{type:'application/json'}),'lc-historial.json');if(a==='clear-history'){localStorage.removeItem('lc-history');render();toast('Historial local eliminado.','ok')}if(a.startsWith('download-history-')){const x=history()[+a.split('-').pop()];if(x?.report)download(new Blob([x.report],{type:'text/plain'}),`lc-${x.name}.txt`)}if(a==='autosave'){const on=localStorage.getItem('lc-autosave')==='true';localStorage.setItem('lc-autosave',String(!on));render();toast('Preferencia actualizada.','ok')}})}
window.addEventListener('hashchange',render);window.addEventListener('DOMContentLoaded',render);